version: "2"

# A Docker Compose file for configuration of the development environment

services:
  lb:
    extends:
      file: docker-compose-common.yml
      service: lb
    image: cs373sweg/db_test_lb
    environment:
      # Always deploy to n1 so the lb always has the same IP address. This is
      # just for convenience and isn't strictly necessary.
      - "constraint:node==*n1"

  # app
  app:
    extends:
      file: docker-compose-common.yml
      service: app
    ports:
      # Publish the port so it's visible on the host, you can access the app directly
      - "8000:8000"
    volumes:
      # Mount the app dir in the container as /src so our changes to the app code
      # are also changed in the container
      - ./app:/src
    command: gunicorn --reload app:app --bind 0.0.0.0:8000
      # Run Gunicorn to serve app requests and reload on change so we can see our
      # changes to the app code

networks:
  backend: {}
